USE WideWorldImporters
GO
-- COMPATIBILITY_LEVEL 160 == SQL Server 2022
ALTER DATABASE WideWorldImporters SET COMPATIBILITY_LEVEL = 160;
GO
-- PARAMETER_SENSITIVE_PLAN_OPTIMIZATION is enabled by default
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SENSITIVE_PLAN_OPTIMIZATION = ON;
GO
